repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: seed-isort-config
        name: seed-isort-config
        entry: seed-isort-config
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        exclude: tests
      - id: beautysh
        name: beautysh
        description: "beautifysh all shell scripts"
        entry: beautysh
        language: python
        types: [shell]
      - id: check-for-yq
        name: Check for workable yq
        language: system
        entry: |
          bash -c "which yq"
      - id: jq
        name: jq
        description: "jq all json files"
        entry: |
          jq . -
        language: system
        types: [json]
      - id: yq
        name: yq
        description: "yq all yaml files"
        entry: |
          yq . -
        language: system
        types: [yaml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-xml
      - id: check-toml
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: check-merge-conflict
